on:
  push:
    paths:
      - 'cafeteria-spring/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' 
          java-version: '21'
#      - name: change dir
#        run: cd cafeteria-spring
      - name: Build and test
        run: chmod +x ./cafeteria-spring/mvnw
      - name: build
        run: ./cafeteria-spring/mvnw clean package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./cafeteria-spring/Dockerfile
          push: true
          tags: sujith071/springrepo:latest
