on:
  push:
    paths:
      - 'cafeteria-spring/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' 
          java-version: '21'
#      - name: change dir
#        run: cd cafeteria-spring
      # - run: ls
      #   working-directory: ./cafeteria-spring
      - name: Build and test
        run: chmod +x mvnw
        working-directory: ./cafeteria-spring

      - name: build
        run: ./mvnw clean package
        working-directory: ./cafeteria-spring
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # - run: ls
      #   working-directory: ./cafeteria-spring/target
      
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cafeteria-spring
          file: ./cafeteria-spring/Dockerfile
          push: true
          tags: sujith071/springrepo:${{github.run_number}}
          working-directory: ./cafeteria-spring
          
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
 
      - name: Login to  Docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: check images
        run: docker images
      - name: build elastic search image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1
 
      - name: build springboot image
        run: docker pull sujith071/springrepo
 
      - name: build angular image
        run: docker pull sujith071/angularrepo
 
 
      - name: docker compose
        run: docker compose up
  
