
on:
  push:
    paths:
      - "cafeteria-angular/**"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    environment: myenvironment
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # - run: ls

      # - name: change dir
      #   run: cd ./cafeteria-angular

      # - run: ls

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cafeteria-angular
          file: ./cafeteria-angular/Dockerfile
          push: true
          tags: sujith071/angularrepo
          working-directory: ./cafeteria-angular
  deploy:
    runs-on: self-hosted
    needs: push_to_registry
    steps:
      - uses: actions/checkout@v4
 
      - name: Login to  Docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: check images
        run: docker images
      - name: build elastic search image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1
 
      - name: build springboot image
        run: docker pull sujith071/springrepo
 
      - name: build angular image
        run: docker pull sujith071/angularrepo
 
 
      - name: docker compose
        run: docker-compose up && docker-compose rm -fs
          
