
on:
  push:
    paths:
      - "cafeteria-angular/**"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: myenvironment
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - run: ls

      - name: change dir
        run: cd ./cafeteria-angular

      - run: ls

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cafeteria-angular
          file: ./cafeteria-angular/Dockerfile
          push: true
          tags: sujith071/angularrepo:latest
          working-directory: ./cafeteria-angular
          
