name: Docker Build and Push

on:
  push:
    paths:
      - 'cafeteria-angular/**'
      - 'cafeteria-spring/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Angular Docker Image
        if: contains(github.event_name, 'push') && contains(github.ref, 'refs/heads/main') && github.path == 'cafeteria-angular'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          cd cafeteria-angular
          docker build -t sujith071/angularrepo:latest .
          docker push sujith071/angularrepo:latest

      - name: Build Spring Boot JAR and Docker Image
        if: contains(github.event_name, 'push') && contains(github.ref, 'refs/heads/main') && github.path == 'cafeteria-spring'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd cafeteria-spring
          ./mvnw clean package 
          docker build -t sujith071/springrepo:latest .
          docker push sujith071/springrepo:latest
